Repository 4-mul-meong/backend-batch, pull requests merged in 2024-12, with the labels that each got.

#6 [🚀 Batch] CI/CD 환경 구축
  .github/workflows/ci.yaml
  .github/workflows/cicd.yaml
  Dockerfile
Labels: 👷 chore, 🚀 deploy

#2 [🔀 Batch] Contest 정산 기능 구현
  build.gradle
  src/main/java/com/mulmeong/batchserver/BatchServerApplication.java
  src/main/java/com/mulmeong/batchserver/application/EventPublisher.java
  src/main/java/com/mulmeong/batchserver/common/config/KafkaConfig.java
  src/main/java/com/mulmeong/batchserver/common/config/RedisConfig.java
  src/main/java/com/mulmeong/batchserver/common/config/SwaggerConfig.java
  src/main/java/com/mulmeong/batchserver/common/exception/BaseException.java
  src/main/java/com/mulmeong/batchserver/common/exception/GlobalExceptionHandler.java
  src/main/java/com/mulmeong/batchserver/common/health/HealthCheckController.java
  src/main/java/com/mulmeong/batchserver/common/response/BaseResponse.java
  src/main/java/com/mulmeong/batchserver/common/response/BaseResponseStatus.java
  src/main/java/com/mulmeong/batchserver/contest/config/ContestBatchConfig.java
  src/main/java/com/mulmeong/batchserver/contest/config/ContestDatabaseConfig.java
  src/main/java/com/mulmeong/batchserver/contest/config/ContestReadDatabaseConfig.java
  src/main/java/com/mulmeong/batchserver/contest/config/ContestResultBatchConfig.java
  src/main/java/com/mulmeong/batchserver/contest/entity/Kind.java
  src/main/java/com/mulmeong/batchserver/contest/entity/MediaType.java
  src/main/java/com/mulmeong/batchserver/contest/entity/contest/Contest.java
  src/main/java/com/mulmeong/batchserver/contest/entity/contest/ContestPost.java
  src/main/java/com/mulmeong/batchserver/contest/entity/contestRead/ContestPostRead.java
  src/main/java/com/mulmeong/batchserver/contest/infrastructure/repository/ContestPostReadRepository.java
  src/main/java/com/mulmeong/batchserver/contest/infrastructure/repository/ContestPostRepository.java
  src/main/java/com/mulmeong/batchserver/contest/infrastructure/repository/ContestRepository.java
  src/main/java/com/mulmeong/batchserver/presentation/TestController.java
  src/main/java/com/mulmeong/event/contest/produce/ContestStatusEvent.java
  src/main/java/com/mulmeong/event/contest/produce/ContestVoteRecordEvent.java
  src/main/java/com/mulmeong/event/contest/produce/ContestVoteResultEvent.java
  src/main/java/com/mulmeong/event/contest/produce/ContestVoteUpdateEvent.java
Labels: ✨ enhancement

#8 [🚑️ batch] db연결 에러 Resolve
  build.gradle
  src/main/java/com/mulmeong/batchserver/comment/application/FeedCommentService.java
  src/main/java/com/mulmeong/batchserver/comment/application/FeedCommentServiceImpl.java
  src/main/java/com/mulmeong/batchserver/comment/application/FeedRecommentService.java
  src/main/java/com/mulmeong/batchserver/comment/application/FeedRecommentServiceImpl.java
  src/main/java/com/mulmeong/batchserver/comment/application/ShortsCommentService.java
  src/main/java/com/mulmeong/batchserver/comment/application/ShortsCommentServiceImpl.java
  src/main/java/com/mulmeong/batchserver/comment/application/ShortsRecommentService.java
  src/main/java/com/mulmeong/batchserver/comment/application/ShortsRecommentServiceImpl.java
  src/main/java/com/mulmeong/batchserver/comment/config/CommentMongoConfig.java
  src/main/java/com/mulmeong/batchserver/comment/config/FeedCommentBatchConfig.java
  src/main/java/com/mulmeong/batchserver/comment/config/ShortsCommentBatchConfig.java
  src/main/java/com/mulmeong/batchserver/common/config/KafkaConsumerConfig.java
  src/main/java/com/mulmeong/batchserver/contest/config/ContestBatchConfig.java
  src/main/java/com/mulmeong/batchserver/contest/config/ContestMongoConfig.java
  src/main/java/com/mulmeong/batchserver/contest/config/ContestMysqlDatabaseConfig.java
  src/main/java/com/mulmeong/batchserver/contest/config/ContestResultBatchConfig.java
  src/main/java/com/mulmeong/batchserver/feed/application/FeedService.java
  src/main/java/com/mulmeong/batchserver/feed/application/FeedServiceImpl.java
  src/main/java/com/mulmeong/batchserver/feed/config/FeedBatchConfig.java
  src/main/java/com/mulmeong/batchserver/feed/config/FeedMongoConfig.java
  src/main/java/com/mulmeong/batchserver/shorts/application/ShortsService.java
  src/main/java/com/mulmeong/batchserver/shorts/application/ShortsServiceImpl.java
  src/main/java/com/mulmeong/batchserver/shorts/config/ShortsBatchConfig.java
  src/main/java/com/mulmeong/batchserver/shorts/config/ShortsMongoConfig.java
  src/main/java/com/mulmeong/batchserver/utility/application/UtilityKafkaConsumer.java
  src/main/java/com/mulmeong/batchserver/utility/config/UtilityMongoConfig.java
  src/main/java/com/mulmeong/event/utility/consume/DislikeRenewCreateEvent.java
  src/main/java/com/mulmeong/event/utility/consume/LikeRenewCreateEvent.java
Labels: 🐛 bug, 🚑️ hotfix

#10 [🚑️ batch] SpingBootTest 어노테이션 에러 Resolve
  src/test/java/com/mulmeong/batchserver/BatchServerApplicationTests.java
Labels: 🐛 bug

#11 [🚑️ batch] swagger url 에러 Resolve
  src/main/java/com/mulmeong/batchserver/common/config/SwaggerConfig.java
Labels: 🐛 bug

#14 [🚑️ batch] batch server 배포 db 에러 Resolve
  src/main/java/com/mulmeong/batchserver/BatchServerApplication.java
  src/main/java/com/mulmeong/batchserver/comment/config/CommentMongoConfig.java
  src/main/java/com/mulmeong/batchserver/common/config/SwaggerConfig.java
  src/main/java/com/mulmeong/batchserver/contest/config/ContestMongoConfig.java
  src/main/java/com/mulmeong/batchserver/feed/config/FeedMongoConfig.java
  src/main/java/com/mulmeong/batchserver/shorts/config/ShortsMongoConfig.java
  src/main/java/com/mulmeong/batchserver/utility/application/UtilityKafkaConsumer.java
  src/main/java/com/mulmeong/batchserver/utility/config/UtilityMongoConfig.java
  src/test/java/com/mulmeong/batchserver/BatchServerApplicationTests.java
Labels: 🐛 bug

#17 [🚀 batch] 팔로우 시 팔로워, 팔로잉 갱신 기능 구현
  src/main/java/com/mulmeong/batchserver/common/config/KafkaConsumerConfig.java
  src/main/java/com/mulmeong/batchserver/member/config/MemberMongoConfig.java
  src/main/java/com/mulmeong/batchserver/member/domain/document/MemberRead.java
  src/main/java/com/mulmeong/batchserver/member/infrastructure/repository/MemberReadRepository.java
  src/main/java/com/mulmeong/batchserver/utility/application/FollowService.java
  src/main/java/com/mulmeong/batchserver/utility/application/FollowServiceImpl.java
  src/main/java/com/mulmeong/batchserver/utility/application/UtilityKafkaConsumer.java
  src/main/java/com/mulmeong/batchserver/utility/infrastructure/repository/FollowRepository.java
  src/main/java/com/mulmeong/event/utility/consume/FollowCreateEvent.java
Labels: ✨ enhancement

#19 [🚑️ batch] eureka 연결
  build.gradle
  src/main/java/com/mulmeong/batchserver/BatchServerApplication.java
Labels: 🚑️ hotfix

#20 [🚑️ batch] eureka 연결
  build.gradle
  src/main/java/com/mulmeong/batchserver/BatchServerApplication.java
Labels: 🚑️ hotfix

#22 [🔀 batch] comment count update 기능 구현
  src/main/java/com/mulmeong/batchserver/common/config/KafkaConsumerConfig.java
  src/main/java/com/mulmeong/batchserver/feed/application/FeedService.java
  src/main/java/com/mulmeong/batchserver/feed/application/FeedServiceImpl.java
  src/main/java/com/mulmeong/batchserver/shorts/application/ShortsService.java
  src/main/java/com/mulmeong/batchserver/shorts/application/ShortsServiceImpl.java
  src/main/java/com/mulmeong/batchserver/utility/application/UtilityKafkaConsumer.java
  src/main/java/com/mulmeong/event/utility/consume/FeedCommentCreateEvent.java
  src/main/java/com/mulmeong/event/utility/consume/ShortsCommentCreateEvent.java
Labels: ✨ enhancement

#23 [🚀 batch] comment count update
  src/main/java/com/mulmeong/batchserver/common/config/KafkaConsumerConfig.java
  src/main/java/com/mulmeong/batchserver/feed/application/FeedService.java
  src/main/java/com/mulmeong/batchserver/feed/application/FeedServiceImpl.java
  src/main/java/com/mulmeong/batchserver/shorts/application/ShortsService.java
  src/main/java/com/mulmeong/batchserver/shorts/application/ShortsServiceImpl.java
  src/main/java/com/mulmeong/batchserver/utility/application/UtilityKafkaConsumer.java
  src/main/java/com/mulmeong/event/utility/consume/FeedCommentCreateEvent.java
  src/main/java/com/mulmeong/event/utility/consume/ShortsCommentCreateEvent.java
Labels: 🚀 deploy

#25 [🚑️ batch] 어노테이션 에러 Resolve
  src/main/java/com/mulmeong/event/utility/consume/FeedCommentCreateEvent.java
  src/main/java/com/mulmeong/event/utility/consume/ShortsCommentCreateEvent.java
Labels: 🚑️ hotfix

#27 [🚀 batch] unfollow 시 member read 갱신
  src/main/java/com/mulmeong/batchserver/common/config/KafkaConsumerConfig.java
  src/main/java/com/mulmeong/batchserver/utility/application/FollowService.java
  src/main/java/com/mulmeong/batchserver/utility/application/FollowServiceImpl.java
  src/main/java/com/mulmeong/batchserver/utility/application/UtilityKafkaConsumer.java
  src/main/java/com/mulmeong/event/utility/consume/UnfollowEvent.java
Labels: ✨ enhancement

#30 [🚑️ batch] consumer 추가
  src/main/java/com/mulmeong/batchserver/common/config/KafkaConsumerConfig.java
  src/main/java/com/mulmeong/batchserver/utility/application/UtilityKafkaConsumer.java
Labels: 🚑️ hotfix

#33 [🚀 batch] member read batch
  src/main/java/com/mulmeong/batchserver/utility/config/UtilityBatchConfig.java
Labels: 🚀 deploy

#28 [🔀 batch] unfollow 시 member read 갱신
  src/main/java/com/mulmeong/batchserver/comment/infrastructure/repository/FeedCommentReadRepository.java
  src/main/java/com/mulmeong/batchserver/comment/infrastructure/repository/ShortsCommentReadRepository.java
  src/main/java/com/mulmeong/batchserver/common/config/KafkaConsumerConfig.java
  src/main/java/com/mulmeong/batchserver/feed/application/FeedService.java
  src/main/java/com/mulmeong/batchserver/feed/application/FeedServiceImpl.java
  src/main/java/com/mulmeong/batchserver/feed/config/FeedBatchConfig.java
  src/main/java/com/mulmeong/batchserver/shorts/application/ShortsService.java
  src/main/java/com/mulmeong/batchserver/shorts/application/ShortsServiceImpl.java
  src/main/java/com/mulmeong/batchserver/shorts/config/ShortsBatchConfig.java
  src/main/java/com/mulmeong/batchserver/utility/application/FollowService.java
  src/main/java/com/mulmeong/batchserver/utility/application/FollowServiceImpl.java
  src/main/java/com/mulmeong/batchserver/utility/application/UtilityKafkaConsumer.java
  src/main/java/com/mulmeong/batchserver/utility/config/UtilityBatchConfig.java
  src/main/java/com/mulmeong/event/utility/consume/FeedCommentDeleteEvent.java
  src/main/java/com/mulmeong/event/utility/consume/ShortsCommentDeleteEvent.java
  src/main/java/com/mulmeong/event/utility/consume/UnfollowEvent.java
Labels: ✨ enhancement

#35 [🚑️ batch] qualifier 에러 Resolve
  src/main/java/com/mulmeong/batchserver/utility/config/UtilityBatchConfig.java
Labels: 🐛 bug

#37 [🚀 batch] 게시물 수 즉시 갱신, delay 추가
  src/main/java/com/mulmeong/batchserver/comment/config/FeedCommentBatchConfig.java
  src/main/java/com/mulmeong/batchserver/comment/config/ShortsCommentBatchConfig.java
  src/main/java/com/mulmeong/batchserver/feed/config/FeedBatchConfig.java
  src/main/java/com/mulmeong/batchserver/member/application/MemberService.java
  src/main/java/com/mulmeong/batchserver/member/application/MemberServiceImpl.java
  src/main/java/com/mulmeong/batchserver/shorts/config/ShortsBatchConfig.java
  src/main/java/com/mulmeong/batchserver/utility/application/UtilityKafkaConsumer.java
  src/main/java/com/mulmeong/batchserver/utility/config/UtilityBatchConfig.java
Labels: ⚡️ improve

#38 [🚑️ batch] shorts comment delete event 에러 Resolve
  src/main/java/com/mulmeong/batchserver/feed/application/FeedKafkaPublisher.java
  src/main/java/com/mulmeong/batchserver/feed/config/FeedBatchConfig.java
  src/main/java/com/mulmeong/batchserver/utility/application/UtilityKafkaPublisher.java
  src/main/java/com/mulmeong/event/utility/consume/ShortsCommentDeleteEvent.java
  src/main/java/com/mulmeong/event/utility/produce/FeedMetricsUpdateEvent.java
Labels: 🐛 bug

#40 [🚑️ batch] event 수정
  src/main/java/com/mulmeong/event/utility/produce/FeedMetricsUpdateEvent.java
Labels: 🐛 bug
